### ISSUE TITLE
Nitpick: Isn't array insertion always expensive?

### ISSUE THREAD

**Issue by reitzig** [ole/SortedArray#23]
https://github.com/ole/SortedArray/blob/2e6ea067aa11659261b6dc6cf84842b8699fe422/Sources/SortedArray.swift#L46-L48

The comment suggests that insertion in Swift arrays is sometimes cheaper than a full copy.

The [standard doc](https://developer.apple.com/documentation/swift/array/1641389-insert) is not helpful; they only report the "Big-Oh".

[Apparently](http://ankit.im/swift/2016/01/07/exploring-swift-array-implementation/), at least back in 2016, appending elements is cheap if contiguous memory can be allocated after the current buffer; if not, there'd be a full copy.

It seems reasonable to assume that insertion could be similarly sped up, for a total cost of 
 * T_search(n) + T_extend + (n-i)*T_swap in the good case, and 
 * T_search + T_copy(n) in the bad case (no matter at which index we insert).

**Comment by ole** [comment]
I'm not sure what you're asking.

1. [`Array.insert(_:at:)` calls through to `replaceSubrange(_:with:)`](https://github.com/apple/swift/blob/25af770c91bc37adbd9cbc7931c7d54e36f63077/stdlib/public/core/Array.swift#L1273-L1276)

2. `replaceSubrange(_:with:)`

    a. first [grows the buffer if needed](https://github.com/apple/swift/blob/25af770c91bc37adbd9cbc7931c7d54e36f63077/stdlib/public/core/Array.swift#L1552-L1553), i.e. if it hasn't any excess capacity left. This step also copies the buffer if that's required for copy-on-write, i.e. if there's more than one owner. [Source of `requestUniqueMutableBackingBuffer`](https://github.com/apple/swift/blob/master/stdlib/public/core/ArrayBuffer.swift#L156-L166).

    b. It then [calls through to `replaceSubrange(_:with:)`](https://github.com/apple/swift/blob/25af770c91bc37adbd9cbc7931c7d54e36f63077/stdlib/public/core/Array.swift#L1555-L1556) on the buffer.

3. [`ArrayBuffer.replaceSubrange`](https://github.com/apple/swift/blob/master/stdlib/public/core/ArrayBufferProtocol.swift#L148-L224) knows that its buffer is now large enough to accomodate the new elements. It

    a. moves the tail of the collection out of the way (if needed) and
    b. inserts the new element(s) at the correct position.

Let's analyze these steps:

* Step 2a takes O(count) if the buffer needs to be grown. Otherwise it's O(1). We say the overall cost is "amortized O(1)" because if you append many elements, the occasional O(n) growth averages to O(1) per inserted element. This is what the stdlib means when it says "Complexity: O(1) on average, over many additions to the same collection" for `Array.append`.

* Step 3a costs nothing if an element is appended to the end of the array. No existing elements have to be moved. [`tailCount` is 0](https://github.com/apple/swift/blob/master/stdlib/public/core/ArrayBufferProtocol.swift#L166)

* Step 3b costs O(newElements.count) == O(1) for inserting a single element.

Overall, the cost for `insert(_:at:)` is amortized O(1) if the insertion index is at the end of the array.

**Comment by ole** [comment]
I'm going to close this. Feel free to comment/reopen if I haven't answered your question.

**Comment by reitzig** [comment]
> 2a. first grows the buffer if needed, i.e. if it hasn't any excess capacity left. This step also copies the buffer if that's required for copy-on-write
> [...]
> Step 2a takes O(count) if the buffer needs to be grown.

`count` being the number of new elements? The way I understand it, if there is not enough free space immediately behind the current buffer, the whole array/buffer will be copied. That is, growing in such a case is Ω(n). Whether that occurs depends on the heap state, not the implementation alone; it's still misleading to state an O(1) amortized or O(count) upper bound.

Otherwise, the array would not be contiuguous in memory, which I don't think we want.

> We say the overall cost is "amortized O(1)"

That would be accurate (if the implementation did indeed "prefetch" a significant number of empty cells, which the code you link to doesn't seem to do). The code comment I quote doesn't say that. 

> This is what the stdlib means when it says "Complexity: O(1) on average, over many additions to the same collection" for Array.append.

That's unfortunate, because amortized and average-case analysis are not the same thing.

Having read and (I hope) understood your response, I maintain that the code comment in the OP is misleading at best, and very wrong at worst. Since the whole argument for using a SortedArray as efficient implementation rests on this point, either is suboptimal.

FWIW, the idea that a sorted array would be chosen for efficiency clashed so hard with my algorithmic intuition that it made me open this issue. I would expect an efficient search-tree implementation to be superior in most cases; logarithmic expected insertion time (as opposed to linear, which no trickery in the best case gets you out of) is the most significant advantage.
