### ISSUE TITLE
`last(where:...)` uses `firstIndex(where:...)`

### ISSUE THREAD

**Issue by EBGToo** [ole/SortedArray#31]
```
    public func last(where predicate: (Element) throws -> Bool) rethrows -> Element? {
        guard let index = try firstIndex(where: predicate) else { return nil }
        return self[index]
    }
```

presumably should be `lastIndex(where:...)`

**Comment by ole** [comment]
@EBGToo Thank you for the report, this is a serious bug. I pushed a fix in #33.

This made me think, however: the bug is part of the functionality added in #29. I personally never used these features and frankly I don't think anymore they are a good idea. I realized that I never cut a release with these features (due to my generally neglecting to maintain this library for years), so I'm inclined to remove them altogether before making a new release. I have to think about this more.
